/**
 * dummyJsonApi.ts
 *
 * RTK Query API slice for all DummyJSON endpoints.
 * Caching is configured per-endpoint for optimal UX:
 *  - Product lists: 300s (5 min)
 *  - Single products: 120s (2 min)
 *  - Categories: 600s (10 min) — rarely changes
 *  - Auth mutations: no cache (side-effectful)
 */

import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import type { RootState } from '@/lib/store';
import type {
  User,
  LoginRequest,
  RegisterRequest,
  Product,
  ProductsResponse,
  Category,
} from '@/types';

export const dummyJsonApi = createApi({
  reducerPath: 'dummyJsonApi',
  baseQuery: fetchBaseQuery({
    baseUrl: 'https://dummyjson.com',
    /**
     * Attach the JWT Bearer token (from Redux state) to every request.
     * This allows authenticated endpoints to work seamlessly after login.
     */
    prepareHeaders: (headers, { getState }) => {
      const token = (getState() as RootState).auth.token;
      if (token) {
        headers.set('Authorization', `Bearer ${token}`);
      }
      return headers;
    },
  }),

  // ---------------------------------------------------------------------------
  // Tag types for cache invalidation
  // ---------------------------------------------------------------------------
  tagTypes: ['Product', 'Products', 'Categories', 'User'],

  endpoints: (builder) => ({
    // -------------------------------------------------------------------------
    // AUTH
    // -------------------------------------------------------------------------

    /** Login — POST /auth/login */
    login: builder.mutation<User, LoginRequest>({
      query: (credentials) => ({
        url: '/auth/login',
        method: 'POST',
        body: { ...credentials, expiresInMins: 60 },
      }),
    }),

    /**
     * Mock Registration — POST /users/add
     * DummyJSON simulates user creation (does not persist data).
     */
    register: builder.mutation<User, RegisterRequest>({
      query: (userData) => ({
        url: '/users/add',
        method: 'POST',
        body: userData,
      }),
    }),

    // -------------------------------------------------------------------------
    // PRODUCTS
    // -------------------------------------------------------------------------

    /** Fetch paginated products — GET /products?limit=&skip= */
    getProducts: builder.query<ProductsResponse, { limit: number; skip: number }>({
      query: ({ limit, skip }) =>
        `/products?limit=${limit}&skip=${skip}&select=id,title,price,thumbnail,category,rating,stock`,
      // Cache each page separately for 5 minutes
      keepUnusedDataFor: 300,
      providesTags: (result) =>
        result
          ? [
              ...result.products.map(({ id }) => ({ type: 'Product' as const, id })),
              { type: 'Products', id: 'LIST' },
            ]
          : [{ type: 'Products', id: 'LIST' }],
    }),

    /** Search products by title — GET /products/search?q= */
    searchProducts: builder.query<ProductsResponse, { q: string; limit: number; skip: number }>({
      query: ({ q, limit, skip }) =>
        `/products/search?q=${encodeURIComponent(q)}&limit=${limit}&skip=${skip}&select=id,title,price,thumbnail,category,rating,stock`,
      keepUnusedDataFor: 120,
      providesTags: [{ type: 'Products', id: 'SEARCH' }],
    }),

    /** Fetch products by category — GET /products/category/{slug} */
    getProductsByCategory: builder.query<
      ProductsResponse,
      { category: string; limit: number; skip: number }
    >({
      query: ({ category, limit, skip }) =>
        `/products/category/${encodeURIComponent(category)}?limit=${limit}&skip=${skip}&select=id,title,price,thumbnail,category,rating,stock`,
      keepUnusedDataFor: 300,
      providesTags: (result, _error, { category }) =>
        result
          ? [
              ...result.products.map(({ id }) => ({ type: 'Product' as const, id })),
              { type: 'Products', id: `CATEGORY_${category}` },
            ]
          : [{ type: 'Products', id: `CATEGORY_${category}` }],
    }),

    /** Get a single product by ID — GET /products/{id} */
    getProductById: builder.query<Product, number>({
      query: (id) => `/products/${id}`,
      keepUnusedDataFor: 120,
      providesTags: (_result, _error, id) => [{ type: 'Product', id }],
    }),

    // -------------------------------------------------------------------------
    // CATEGORIES
    // -------------------------------------------------------------------------

    /** Fetch all categories — GET /products/categories */
    getCategories: builder.query<Category[], void>({
      query: () => '/products/categories',
      keepUnusedDataFor: 600, // Cache for 10 minutes
      providesTags: ['Categories'],
    }),
  }),
});

// Export typed hooks generated by RTK Query
export const {
  useLoginMutation,
  useRegisterMutation,
  useGetProductsQuery,
  useSearchProductsQuery,
  useGetProductsByCategoryQuery,
  useGetProductByIdQuery,
  useGetCategoriesQuery,
} = dummyJsonApi;
